// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer, foreignKey, index } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const poonChoiOrders = sqliteTable("poon_choi_orders", {
	id: integer().primaryKey({ autoIncrement: true }),
	productType: text("product_type").notNull(),
	quantity: integer().notNull(),
	region: text().notNull(),
	address: text().notNull(),
	deliveryDate: text("delivery_date").notNull(),
	deliveryTime: text("delivery_time").notNull(),
	name: text().notNull(),
	phone: text().notNull(),
	email: text(),
	remarks: text(),
	totalPrice: integer("total_price").notNull(),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
	referralCode: text("referral_code"),
	adminRemarks: text("admin_remarks"),
	language: text().default("zh"),
	campaignName: text("campaign_name").default("poon-choi-good-sung"),
	paymentProof: text("payment_proof"),
	paymentConfirmed: integer("payment_confirmed").default(0).notNull(),
	orderNum: text(),
});

export const referralRecords = sqliteTable("referral_records", {
	id: integer().primaryKey({ autoIncrement: true }),
	referrerPhone: text("referrer_phone").notNull(),
	refereeOrderId: integer("referee_order_id").notNull().references(() => poonChoiOrders.id),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
	refereePhone: text("referee_phone"),
});

export const adminUsers = sqliteTable("admin_users", {
	id: integer().primaryKey({ autoIncrement: true }),
	username: text().notNull(),
	password: text().notNull(),
});

export const whatsappConversations = sqliteTable("whatsapp_conversations", {
	phone: text().primaryKey().notNull(),
	conversationHistory: text("conversation_history").default("[]").notNull(),
	lastMessageAt: integer("last_message_at"),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
	updatedAt: integer("updated_at").default(sql`(unixepoch())`),
	attachments: text().default("[]"),
});

export const whatsappScenarios = sqliteTable("whatsapp_scenarios", {
	id: integer().primaryKey({ autoIncrement: true }),
	scenarioKey: text("scenario_key").notNull(),
	name: text().notNull(),
	defaultLang: text("default_lang").default("zh").notNull(),
	sharePath: text("share_path").default("/").notNull(),
	refCodeStrategy: text("ref_code_strategy").default("phone_last_n").notNull(),
	refCodeN: integer("ref_code_n").default(4).notNull(),
	configJson: text("config_json").default("{}").notNull(),
	isActive: integer("is_active").default(1).notNull(),
	createdAt: integer("created_at").default(sql`(unixepoch())`).notNull(),
	updatedAt: integer("updated_at").default(sql`(unixepoch())`).notNull(),
});

export const whatsappMessageTemplates = sqliteTable("whatsapp_message_templates", {
	id: integer().primaryKey({ autoIncrement: true }),
	scenarioKey: text("scenario_key").notNull().references(() => whatsappScenarios.scenarioKey),
	messageKey: text("message_key").notNull(),
	lang: text().notNull(),
	content: text().notNull(),
	variablesJson: text("variables_json").default("[]").notNull(),
	description: text(),
	isActive: integer("is_active").default(0).notNull(),
	version: integer().default(1).notNull(),
	createdBy: text("created_by"),
	createdAt: integer("created_at").default(sql`(unixepoch())`).notNull(),
	updatedAt: integer("updated_at").default(sql`(unixepoch())`).notNull(),
},
(table) => [
	uniqueIndex("uq_wmt_active_one").on(table.scenarioKey, table.messageKey, table.lang),
	index("idx_wmt_lookup").on(table.scenarioKey, table.messageKey, table.lang, table.isActive),
]);

export const paymentProofUploads = sqliteTable("payment_proof_uploads", {
	id: integer().primaryKey({ autoIncrement: true }),
	orderId: integer("order_id").notNull().references(() => poonChoiOrders.id),
	fileUrl: text("file_url").notNull(),
	fileName: text("file_name"),
	uploadedAt: integer("uploaded_at").default(sql`(unixepoch())`),
	confirmedAt: integer("confirmed_at"),
});

export const uploadLinks = sqliteTable("upload_links", {
	id: integer().primaryKey({ autoIncrement: true }),
	shortCode: text("short_code").notNull(),
	orderId: integer("order_id").notNull().references(() => poonChoiOrders.id),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("idx_upload_links_short_code").on(table.shortCode),
]);

