// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { relations } from "drizzle-orm/relations";
import { orderRecords, referralRecords, whatsappScenarios, whatsappMessageTemplates, paymentProofUploads, uploadLinks } from "./db_schema";

export const referralRecordsRelations = relations(referralRecords, ({one}) => ({
	orderRecord: one(orderRecords, {
		fields: [referralRecords.refereeOrderId],
		references: [orderRecords.id]
	}),
}));

export const orderRecordsRelations = relations(orderRecords, ({many}) => ({
	referralRecords: many(referralRecords),
	paymentProofUploads: many(paymentProofUploads),
	uploadLinks: many(uploadLinks),
}));

export const whatsappMessageTemplatesRelations = relations(whatsappMessageTemplates, ({one}) => ({
	whatsappScenario: one(whatsappScenarios, {
		fields: [whatsappMessageTemplates.scenarioKey],
		references: [whatsappScenarios.scenarioKey]
	}),
}));

export const whatsappScenariosRelations = relations(whatsappScenarios, ({many}) => ({
	whatsappMessageTemplates: many(whatsappMessageTemplates),
}));

export const paymentProofUploadsRelations = relations(paymentProofUploads, ({one}) => ({
	orderRecord: one(orderRecords, {
		fields: [paymentProofUploads.orderId],
		references: [orderRecords.id]
	}),
}));

export const uploadLinksRelations = relations(uploadLinks, ({one}) => ({
	orderRecord: one(orderRecords, {
		fields: [uploadLinks.orderId],
		references: [orderRecords.id]
	}),
}));
