-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE admin_users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE payment_proof_uploads (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  order_id INTEGER NOT NULL UNIQUE,
  file_url TEXT NOT NULL,
  file_name TEXT,
  uploaded_at INTEGER DEFAULT (unixepoch()),
  confirmed_at INTEGER,
  FOREIGN KEY (order_id) REFERENCES order_records(id)
);

CREATE TABLE order_records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  product_type TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  region TEXT NOT NULL,
  address TEXT NOT NULL,
  delivery_date TEXT NOT NULL,
  delivery_time TEXT NOT NULL,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  remarks TEXT,
  total_price INTEGER NOT NULL,
  created_at INTEGER DEFAULT (unixepoch())
, referral_code TEXT, admin_remarks TEXT, language TEXT DEFAULT 'zh', campaign_name TEXT DEFAULT 'poon-choi-good-sung', payment_proof TEXT, payment_confirmed INTEGER NOT NULL DEFAULT 0, orderNum TEXT);

CREATE TABLE referral_records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  referrer_phone TEXT NOT NULL,
  referee_order_id INTEGER NOT NULL REFERENCES order_records(id),
  created_at INTEGER DEFAULT (unixepoch())
, referee_phone TEXT);

CREATE TABLE upload_links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  short_code TEXT NOT NULL UNIQUE,
  order_id INTEGER NOT NULL UNIQUE,
  created_at INTEGER DEFAULT (unixepoch()),
  FOREIGN KEY (order_id) REFERENCES order_records(id)
);

CREATE TABLE whatsapp_conversations (
  phone TEXT PRIMARY KEY NOT NULL,
  conversation_history TEXT NOT NULL DEFAULT '[]',
  last_message_at INTEGER,
  created_at INTEGER DEFAULT (unixepoch()),
  updated_at INTEGER DEFAULT (unixepoch())
, attachments TEXT DEFAULT '[]');

CREATE TABLE whatsapp_message_templates (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  scenario_key TEXT NOT NULL,
  message_key TEXT NOT NULL,
  lang TEXT NOT NULL,
  content TEXT NOT NULL,
  variables_json TEXT NOT NULL DEFAULT '[]',
  description TEXT,
  is_active INTEGER NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 1,
  created_by TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
  FOREIGN KEY (scenario_key) REFERENCES whatsapp_scenarios(scenario_key)
);

CREATE TABLE whatsapp_scenarios (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  scenario_key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  default_lang TEXT NOT NULL DEFAULT 'zh',
  share_path TEXT NOT NULL DEFAULT '/',
  ref_code_strategy TEXT NOT NULL DEFAULT 'phone_last_n',
  ref_code_n INTEGER NOT NULL DEFAULT 4,
  config_json TEXT NOT NULL DEFAULT '{}',
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- INDEXS

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);

CREATE INDEX idx_upload_links_short_code ON upload_links(short_code);

CREATE INDEX idx_wmt_lookup ON whatsapp_message_templates(scenario_key, message_key, lang, is_active);

CREATE UNIQUE INDEX uq_wmt_active_one ON whatsapp_message_templates(scenario_key, message_key, lang) WHERE is_active = 1;
